<?php
 $usuarios[]=[
"alias"=>'wasp',
"nombre"=>'vass',
"apellido"=>'vass',
"pais"=>'Argentina',
"email"=>'una_simple_vida@live.com',
"password"=>'hombre1986',
"img_name"=>'01.jpg',
"user"=>true,
"id"=>'191wasp',
"compras"=>0,
"dinero"=>0,
]; 
$usuarios[]=[
"alias"=>'romina',
"nombre"=>'vallesteros',
"apellido"=>'de los montes',
"pais"=>'Argentina',
"email"=>'blabla@gmail.com',
"password"=>'hombre1986',
"user"=>true,
"id"=>'191wasp',
"compras"=>0,
"dinero"=>0,
]; 