<?php
 $usuarios[]=[
"alias"=>'wasp',
"nombre"=>'vass',
"apellido"=>'vass',
"pais"=>'Argentina',
"email"=>'una_simple_vida@live.com',
"password"=>'hombre1986',
"user"=>true,
"id"=>'191wasp',
"compras"=>0,
"dinero"=>0,
]; 